import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // add begin
  pythonSidebar:   [{type: 'autogenerated', dirName: 'python'}],
  dbSidebar:       [{type: 'autogenerated', dirName: 'db'}],
  ccnaSidebar:     [{type: 'autogenerated', dirName: 'ccna'}],
  linuxSidebar:    [{type: 'autogenerated', dirName: 'linux'}],
  githubSidebar:   [{type: 'autogenerated', dirName: 'github'}],
  markdownSidebar: [{type: 'autogenerated', dirName: 'markdown'}],
  vimSidebar:      [{type: 'autogenerated', dirName: 'vim'}],
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  /*
  pythonSidebar: [
    { type: 'doc', id: 'python/syntax' },
    { type: 'doc', id: 'python/venv' },
    { type: 'doc', id: 'python/pandas-basics' },
  ],

  dbSidebar: [
    { type: 'doc', id: 'db/intro' },
    { type: 'doc', id: 'db/normalization' },
    { type: 'doc', id: 'db/sql-joins' },
  ],

  ccnaSidebar: [
    { type: 'doc', id: 'ccna/intro' },
    { type: 'doc', id: 'ccna/ospf' },
    { type: 'doc', id: 'ccna/acl' },
    { type: 'doc', id: 'ccna/nat' },
  ],

  linuxSidebar: [
    { type: 'doc', id: 'linux/basic-linux' },
    { type: 'doc', id: 'linux/file-permissions' },
  ],
  */
  // add end

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
